config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'assign', to: 'assign#index', as: 'assigns'
  get 'assign/:id', to: 'assign#show', as: 'assign'
  get 'teams', to: 'teams#index', as: 'teams'
  get 'scores', to: 'scores#index', as: 'scores'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'scores#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: people
#
#  id         :bigint           not null, primary key
#  name       :string           default(""), not null
#  score      :decimal          default(0.0), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  team_id    :bigint
#
# Indexes
#
#  index_challenge_on_name  (name) UNIQUE
#

class Challenge < ApplicationRecord
    belongs_to :team, optional: true
end

app/models/person.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: people
#
#  id         :bigint           not null, primary key
#  name       :string           default(""), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  team_id    :bigint
#
# Indexes
#
#  index_people_on_name  (name) UNIQUE
#

# A person, a member of the company
class Person < ApplicationRecord
  belongs_to :team, optional: true

  def confirm_team
    return if team_id.present?

    base_counts = team_counts
    counts_in_use = base_counts.select { |x| x[1] < base_counts[0][1] + 2 }
    update(team_id: counts_in_use.sample[0])
    reload
  end

  private

  def team_counts
    Person
      .joins(:team)
      .group(:team_id)
      .order('2 ASC, 1 ASC')
      .pluck(:team_id, Arel.sql('count(*)'))
  end
end

app/models/sentence.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: sentences
#
#  id         :bigint           not null, primary key
#  content    :string           default(""), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Sentence < ApplicationRecord
end

app/models/team.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: teams
#
#  id         :bigint           not null, primary key
#  color1     :string           default(""), not null
#  color2     :string           default(""), not null
#  creature   :string           default(""), not null
#  founder    :string           default(""), not null
#  name       :string           default(""), not null
#  values     :string           default([]), not null, is an Array
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_teams_on_name  (name) UNIQUE
#

# A team, like a house of Gryffindor
class Team < ApplicationRecord
  has_many :people, dependent: :destroy
  has_many :challenges, dependent: :nullify

  has_one_attached :avatar

  before_update :clean_empty_values

  def score
    challenges.inject(0.0) do |score, challenge| 
      score + challenge.score
    end
  end

  private

  def clean_empty_values
    values.reject!(&:blank?)
  end
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  active                 :boolean          default(FALSE), not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

# Application user
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Base controller
class ApplicationController < ActionController::Base
  private

  def authenticate_and_check_active!
    if current_user.nil?
      flash[:alert] = 'You have to sign in'
      redirect_to new_user_session_path
    elsif !current_user.active?
      sign_out
      flash[:alert] = 'Your account is not active'
      redirect_to new_user_session_path
    end
  end
end

app/controllers/assign_controller.rb
# frozen_string_literal: true

# Controller for people management
class AssignController < ApplicationController
  def index
    @people = Person.all.order(id: :asc)
  end

  def show
    @person = Person.includes(:team).find(params[:id])
    @person.confirm_team
    @team = @person.team
    @sentences = Sentence.all.pluck(:content).sample(4)
  end
end

app/controllers/scores_controller.rb
# frozen_string_literal: true

# Team scores
class ScoresController < ApplicationController
  def index
    @teams = Team.includes(:challenges).sort_by {
      |team| team.score
    }.reverse
  end
end

app/controllers/teams_controller.rb
# frozen_string_literal: true

# Controller used to show team rosters
class TeamsController < ApplicationController
  def index
    @teams = Team.includes(:people).sort_by {
      |team| team.score
    }.reverse
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/assign_helper.rb
# frozen_string_literal: true

module AssignHelper
end

app/helpers/scores_helper.rb
# frozen_string_literal: true

module ScoresHelper
end

app/helpers/teams_helper.rb
# frozen_string_literal: true

module TeamsHelper
end

app/views/assign/index.html.erb
<div class="o-container">
  <div class="o-grid">
    <% @people.each do |person| %>
      <div class="o-grid__el u-size-12/12 u-size-12/12@xs u-size-6/12@md u-size-3/12@xl">
        <%= link_to assign_path(person.id), class: 'c-button__link' do%>
          <button class="c-button c-button-grid"><%= person.name %></button>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/assign/show.html.erb
<div class="o-container o-container--flex">
  <div class="o-list">
    <div class="o-sorting_qat_image" style="background-image: url(<%= image_path('sorting_qat1.jpg') %>)"></div>
    <div class="o-list-el o-list-rolling" id="sentences">
    </div>
  </div>
  <div class="o-assign_image--container">
    <% if @team.avatar.attached? %>
      <div class="o-assign_image" id="team-image" style="background-image: url(<%= url_for(@team.avatar) %>);"></div>
    <% else %>
      <div class="o-assign_image" id="team-image">
        <h1><%= @team.name %></h1>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", function() {
    var sentences = <%= raw @sentences %>;
    var decision = "<%= raw "I pick #{@team.name}!" %>";

    function changeLine(content) {
      var new_el = document.createElement('h1');
      new_el.classList.add('o-list-el');
      new_el.innerHTML = content;
      var el = document.getElementById('sentences');
      el.replaceChild(new_el, el.firstChild);
    }

    function addSentence(content, time) {
      setTimeout(function() {
        changeLine(content);
      }, time);
    };

    for (var i = 0; i < sentences.length; i++) {
      addSentence(sentences[i], 2500*(i+1));
    }
    addSentence('Hmm...',0);
    addSentence('...', 12000);
    addSentence(decision, 14000);

    setTimeout(function(){
      document.getElementById('team-image').classList.add('show');
    }, 14000);
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag %>

    <title>Winter retreat</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="o-skeleton">
      <div class="o-skeleton__head">
        <%= render 'layouts/components/navbar' %>
      </div>
      <div class="o-skeleton__main">
        <% if notice %>
          <p><%= notice %></p>
        <% end %>
        <% if alert %>
          <p><%= alert %></p>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/components/_navbar.html.erb
<div class="c-navbar">
  <div class="c-navbar__navigation">
    <div class="c-navbar__link-area <%= 'active' if current_page?(teams_path) %>">
      <%= link_to 'Teams', teams_path, class: 'c-navbar__link' %>
    </div>
    <div class="c-navbar__link-area <%= 'active' if current_page?(scores_path) %>">
      <%= link_to 'Scores', scores_path, class: 'c-navbar__link' %>
    </div>
    <div class="c-navbar__link-area <%= 'active' if controller_name == 'assign' %>">
      <%= link_to 'Assign', assigns_path, class: 'c-navbar__link' %>
    </div>
  </div>
</div>

app/views/scores/index.html.erb
<div class="o-container">
  <div class="o-list">
    <% @teams.each do |team| %>
      <div class="o-list-el">
        <h1><%= team.name %>: &nbsp; <%= team.score %> points!</h1>
        <% team.challenges.each do |challenge| %>
          <%= render partial: 'scores/partials/challenge_details', locals: {challenge: challenge} %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/scores/partials/_challenge_details.html.erb
<h2> <%= challenge.name %> : <%= challenge.score %> pts </h2>